apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargo-app
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/Amungun/argocd
    targetRevision: HEAD
    path: dev
destination: https://kubernetes.default.svc
